
trigger:
  branches:
    include:
    - 'azure-pipelines' 

pool:
  vmImage: ubuntu-latest

container: mcr.microsoft.com/playwright:v1.21.1-focal
  
steps:
- script: |
    npm ci
    npx playwright test
  displayName: 'Run Playwright Tests'
  workingDirectory: todomvc

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'todomvc/test-results/junit-results.xml'
    failTaskOnFailedTests: true
    testRunTitle: 'Playwright Tests'