
trigger:
  branches:
    include:
    - 'azure-pipelines' 

pool:
  vmImage: ubuntu-latest

container: mcr.microsoft.com/playwright:v1.21.1-focal

steps:
- script: npx playwright test
  displayName: 'Run Playwright Tests'
  workingDirectory: todomvc

