# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
container: mcr.microsoft.com/playwright:v1.22.0-focal

steps:
- script: npx playwright test
  displayName: 'Run Playwright Tests'
  workingDirectory: todomvc

